# This file was created with the Mesa Configuration Tool on Aug 03 2026 17:08:35
# Changes to most things are ok and will be read by the Configuration Tool

[MESA]
VERSION = 2.1.8
BOARD = 7i96s
BOARD_NAME = 7i96s
CARD_0 = 7i84

[EMC]
VERSION = 1.1
MACHINE = BigRedCNC
DEBUG = 0x00000000

[HM2]
DRIVER = hm2_eth
ADDRESS = 10.10.10.10

[DISPLAY]
# required NativeCAM item :
NCAM_DIR = ncam

# required NativeCAM item :
#GLADEVCP = -U --catalog=mill /usr/share/linuxcnc/aux_gladevcp/NativeCAM/ncam.ui
EMBED_TAB_NAME = NativeCAM
EMBED_TAB_COMMAND = gladevcp -x {XID} -U --catalog=mill /usr/share/linuxcnc/aux_gladevcp/NativeCAM/ncam.ui

DISPLAY = axis
EDITOR = geany
# required NativeCAM item :
PROGRAM_PREFIX = ncam/scripts/

POSITION_OFFSET = RELATIVE
POSITION_FEEDBACK = COMMANDED
MAX_FEED_OVERRIDE = 15
MIN_LINEAR_VELOCITY = 0.0
DEFAULT_LINEAR_VELOCITY = 100.0
MAX_LINEAR_VELOCITY = 334.0
MIN_ANGULAR_VELOCITY = 0.0
DEFAULT_ANGULAR_VELOCITY = 0.0
MAX_ANGULAR_VELOCITY = 0.0
CYCLE_TIME = 0.1
INTRO_GRAPHIC = emc2.gif
INTRO_TIME = 0
OPEN_FILE = ""
PYVCP = panel.xml
INCREMENTS = 100mm, 50mm, 10mm, 5mm, 1mm, 0.5mm, 0.1mm, 0.05mm, 0.01mm

[KINS]
KINEMATICS = trivkins coordinates=XYZ kinstype=BOTH
JOINTS = 3

[EMCIO]
EMCIO = iov2
CYCLE_TIME = 0.100
TOOL_TABLE = tool.tbl

[RS274NGC]
# required NativeCAM item :
SUBROUTINE_PATH = ncam/my-stuff:ncam/lib/mill:ncam/lib/utilities

PARAMETER_FILE = parameters.var

[EMCMOT]
EMCMOT = motmod
COMM_TIMEOUT = 1.0
SERVO_PERIOD = 2000000

[TASK]
TASK = milltask
CYCLE_TIME = 0.010

[TRAJ]
COORDINATES = XYZ
LINEAR_UNITS = mm
ANGULAR_UNITS = degree
MAX_LINEAR_VELOCITY = 333.4


[HAL]
TWOPASS = ON
HALFILE = bigredcnc.hal
HALFILE = bigredcnc_Xaxis.hal
HALFILE = bigredcnc_Yaxis.hal
HALFILE = bigredcnc_Zaxis.hal
HALFILE = bigredcnc_Spindle.hal
HALFILE = bigredcnc_Toolchange.hal
HALFILE = io.hal
HALFILE = custom.hal
POSTGUI_HALFILE = postgui.hal
HALUI = halui

[HALUI]

[AXIS_X]
MIN_LIMIT = -85
MAX_LIMIT = 2600
MAX_VELOCITY = 333
MAX_ACCELERATION = 1200

[JOINT_0]
CARD = 1
TAB = 0
AXIS = X
MIN_LIMIT = -85
MAX_LIMIT = 2600
MAX_VELOCITY = 333
MAX_ACCELERATION = 1200
TYPE = LINEAR
SCALE = 15.92458401
STEP_INVERT = False
DIR_INVERT = False
STEPGEN_MAX_VEL = 399.60
STEPGEN_MAX_ACC = 2880.00
DIRSETUP = 5000
DIRHOLD = 5000
STEPLEN = 5000
STEPSPACE = 5000
FERROR =  00.005
MIN_FERROR =  0.0025
HOME = 2500
HOME_OFFSET = 2600
HOME_SEARCH_VEL = 200
HOME_LATCH_VEL = 50
HOME_FINAL_VEL = 100
HOME_IGNORE_LIMITS = True
HOME_SEQUENCE = 2

[AXIS_Y]
MIN_LIMIT = -30
MAX_LIMIT = 1250
MAX_VELOCITY = 334
MAX_ACCELERATION = 1200

[JOINT_1]
AXIS = Y
MIN_LIMIT = -30
MAX_LIMIT = 1250
MAX_VELOCITY = 334
MAX_ACCELERATION = 1200
TYPE = LINEAR
SCALE = 15.92458401
STEP_INVERT = False
DIR_INVERT = False
STEPGEN_MAX_VEL = 400.80
STEPGEN_MAX_ACC = 2880.00
DIRSETUP = 5000
DIRHOLD = 5000
STEPLEN = 5000
STEPSPACE = 5000
FERROR = 0.005
MIN_FERROR =  0.0025
HOME = 1220
HOME_OFFSET = 1250
HOME_SEARCH_VEL = 200
HOME_LATCH_VEL = 50
HOME_FINAL_VEL = 50
HOME_IGNORE_LIMITS = True
HOME_SEQUENCE = 1

[AXIS_Z]
MIN_LIMIT = -200
MAX_LIMIT = 20
MAX_VELOCITY = 100
MAX_ACCELERATION = 1200

[JOINT_2]
AXIS = Z
MIN_LIMIT = -200
MAX_LIMIT = 20
MAX_VELOCITY = 100
MAX_ACCELERATION = 1200
TYPE = LINEAR
SCALE = 200
STEP_INVERT = False
DIR_INVERT = False
STEPGEN_MAX_VEL = 120.00
STEPGEN_MAX_ACC = 2880.00
DIRSETUP = 5000
DIRHOLD = 5000
STEPLEN = 5000
STEPSPACE = 5000
FERROR =  0.005
MIN_FERROR =  0.0025
HOME = 0
HOME_OFFSET = 20
HOME_SEARCH_VEL = 100
HOME_LATCH_VEL = 50
HOME_FINAL_VEL = 10
HOME_IGNORE_LIMITS = True
HOME_SEQUENCE = 0

[SPINDLE_0]
MAX_RPM = 24000
MIN_RPM = 3000

