#!/usr/bin/env python
# coding: utf-8
import os
import gi
gi.require_version('Gtk', '3.0')
from gi.repository import Gtk as gtk, GdkPixbuf

fname = '/home/freemoore/linuxcnc/configs/morb01/ncam/catalogs/no_skip_dlg.conf'
if os.path.isfile(fname) :
    exit(0)

msg = 'Stop LinuxCNC program,&#10;toggle the shown button,&#10;then restart'
msg1 = 'Skip block not active'
icon_fname = '/home/freemoore/linuxcnc/configs/morb01/ncam/graphics/skip_block.png'

dlg = gtk.MessageDialog(parent = None, flags = gtk.DialogFlags.MODAL | gtk.DialogFlags.DESTROY_WITH_PARENT, type = gtk.MessageType.WARNING, buttons = gtk.ButtonsType.NONE, message_format = msg1)

dlg.set_title('NativeCAM')
dlg.format_secondary_markup(msg)

img = gtk.Image()
img.set_from_pixbuf(GdkPixbuf.Pixbuf.new_from_file_at_size(icon_fname, 80, 80))
dlg.get_message_area().pack_start(img, True, True, 0)

cb = gtk.CheckButton(label = "Do not show again")
dlg.get_content_area().pack_start(cb, True, True, 0)
dlg.add_button("gtk-ok", gtk.ResponseType.OK).grab_focus()

dlg.set_keep_above(True)
dlg.show_all()
dlg.run()
if cb.get_active() :
    open(fname, 'w').close()
exit(0)
